// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package kr.miraesoft.simplebook.web;

import kr.miraesoft.simplebook.web.BookBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BookBean_Roo_Configurable {
    
    declare @type: BookBean: @Configurable;
    
}
